// My Profile app
// eslint-disable-next-line no-shadow
export enum DialogType {
  MY_PROFILE_UPDATE_NAME = 'MY_PROFILE_UPDATE_NAME',
  MY_PROFILE_UPDATE_BIRTHDAY = 'MY_PROFILE_UPDATE_BIRTHDAY',
  MY_PROFILE_UPDATE_PHONE = 'MY_PROFILE_UPDATE_PHONE',
}
